baseURL = 'https://example.org/'
locale = 'en-us'
title = '2D Noise Generator Showcase'
disableKinds = ['taxonomy', 'term']

[params]
  description = "A site about 2D noise textures"
  author = "Xavier Alvarez"
  keywords = ""